# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_protobuf/light_header/extra_sensors/hardware_description.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_protobuf/light_header/extra_sensors/hardware_description.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nAlt_protobuf/light_header/extra_sensors/hardware_description.proto\x12\x04ltpb\"\x91\x01\n\x13HardwareDescription\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\x12\x14\n\x0cmanufacturer\x18\x02 \x01(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\t\x12\x12\n\nfw_version\x18\x04 \x01(\t\x12\x12\n\nhw_version\x18\x05 \x01(\t\x12\x15\n\rserial_number\x18\x06 \x01(\tb\x06proto3'
)




_HARDWAREDESCRIPTION = _descriptor.Descriptor(
  name='HardwareDescription',
  full_name='ltpb.HardwareDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ltpb.HardwareDescription.device_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='ltpb.HardwareDescription.manufacturer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='ltpb.HardwareDescription.product_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fw_version', full_name='ltpb.HardwareDescription.fw_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hw_version', full_name='ltpb.HardwareDescription.hw_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='ltpb.HardwareDescription.serial_number', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['HardwareDescription'] = _HARDWAREDESCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HardwareDescription = _reflection.GeneratedProtocolMessageType('HardwareDescription', (_message.Message,), {
  'DESCRIPTOR' : _HARDWAREDESCRIPTION,
  '__module__' : 'lt_protobuf.light_header.extra_sensors.hardware_description_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.HardwareDescription)
  })
_sym_db.RegisterMessage(HardwareDescription)


# @@protoc_insertion_point(module_scope)
