# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_protobuf/light_header/extra_sensors/lidar_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lt_protobuf.common import camera_id_pb2 as lt__protobuf_dot_common_dot_camera__id__pb2
from lt_protobuf.common import point3f_pb2 as lt__protobuf_dot_common_dot_point3f__pb2
from lt_protobuf.light_header.extra_sensors import lidar_data_ouster_pb2 as lt__protobuf_dot_light__header_dot_extra__sensors_dot_lidar__data__ouster__pb2
from lt_protobuf.light_header.extra_sensors import hardware_description_pb2 as lt__protobuf_dot_light__header_dot_extra__sensors_dot_hardware__description__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_protobuf/light_header/extra_sensors/lidar_data.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n7lt_protobuf/light_header/extra_sensors/lidar_data.proto\x12\x04ltpb\x1a\"lt_protobuf/common/camera_id.proto\x1a lt_protobuf/common/point3f.proto\x1a>lt_protobuf/light_header/extra_sensors/lidar_data_ouster.proto\x1a\x41lt_protobuf/light_header/extra_sensors/hardware_description.proto\"\xa4\x01\n\x0bLidarHwInfo\x12+\n\x05model\x18\x01 \x01(\x0e\x32\x1c.ltpb.LidarHwInfo.LidarModel\x12\x31\n\x0ehw_description\x18\x02 \x01(\x0b\x32\x19.ltpb.HardwareDescription\"5\n\nLidarModel\x12\x13\n\x0fVELODYNE_VLP32C\x10\x00\x12\x12\n\x0eOUSTER_OS2_128\x10\x01\"\xaa\x01\n\x10LidarCalibration\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\x12\x33\n\x12ouster_calibration\x18\x02 \x01(\x0b\x32\x17.ltpb.OusterCalibration\x12\x36\n\x0b\x64\x61ta_format\x18\x03 \x01(\x0e\x32!.ltpb.LidarCalibration.DataFormat\"\x16\n\nDataFormat\x12\x08\n\x04PCAP\x10\x00\"\x9f\x01\n\x16LidarCameraCalibration\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\x12%\n\rcamera_module\x18\x02 \x01(\x0e\x32\x0e.ltpb.CameraID\x12$\n\reuler_xyz_rad\x18\x03 \x01(\x0b\x32\r.ltpb.Point3F\x12%\n\x0etranslation_mm\x18\x04 \x01(\x0b\x32\r.ltpb.Point3Fb\x06proto3'
  ,
  dependencies=[lt__protobuf_dot_common_dot_camera__id__pb2.DESCRIPTOR,lt__protobuf_dot_common_dot_point3f__pb2.DESCRIPTOR,lt__protobuf_dot_light__header_dot_extra__sensors_dot_lidar__data__ouster__pb2.DESCRIPTOR,lt__protobuf_dot_light__header_dot_extra__sensors_dot_hardware__description__pb2.DESCRIPTOR,])



_LIDARHWINFO_LIDARMODEL = _descriptor.EnumDescriptor(
  name='LidarModel',
  full_name='ltpb.LidarHwInfo.LidarModel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VELODYNE_VLP32C', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUSTER_OS2_128', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=378,
  serialized_end=431,
)
_sym_db.RegisterEnumDescriptor(_LIDARHWINFO_LIDARMODEL)

_LIDARCALIBRATION_DATAFORMAT = _descriptor.EnumDescriptor(
  name='DataFormat',
  full_name='ltpb.LidarCalibration.DataFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PCAP', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=582,
  serialized_end=604,
)
_sym_db.RegisterEnumDescriptor(_LIDARCALIBRATION_DATAFORMAT)


_LIDARHWINFO = _descriptor.Descriptor(
  name='LidarHwInfo',
  full_name='ltpb.LidarHwInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='ltpb.LidarHwInfo.model', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hw_description', full_name='ltpb.LidarHwInfo.hw_description', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LIDARHWINFO_LIDARMODEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=431,
)


_LIDARCALIBRATION = _descriptor.Descriptor(
  name='LidarCalibration',
  full_name='ltpb.LidarCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ltpb.LidarCalibration.device_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ouster_calibration', full_name='ltpb.LidarCalibration.ouster_calibration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_format', full_name='ltpb.LidarCalibration.data_format', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LIDARCALIBRATION_DATAFORMAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=604,
)


_LIDARCAMERACALIBRATION = _descriptor.Descriptor(
  name='LidarCameraCalibration',
  full_name='ltpb.LidarCameraCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ltpb.LidarCameraCalibration.device_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_module', full_name='ltpb.LidarCameraCalibration.camera_module', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='euler_xyz_rad', full_name='ltpb.LidarCameraCalibration.euler_xyz_rad', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation_mm', full_name='ltpb.LidarCameraCalibration.translation_mm', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=766,
)

_LIDARHWINFO.fields_by_name['model'].enum_type = _LIDARHWINFO_LIDARMODEL
_LIDARHWINFO.fields_by_name['hw_description'].message_type = lt__protobuf_dot_light__header_dot_extra__sensors_dot_hardware__description__pb2._HARDWAREDESCRIPTION
_LIDARHWINFO_LIDARMODEL.containing_type = _LIDARHWINFO
_LIDARCALIBRATION.fields_by_name['ouster_calibration'].message_type = lt__protobuf_dot_light__header_dot_extra__sensors_dot_lidar__data__ouster__pb2._OUSTERCALIBRATION
_LIDARCALIBRATION.fields_by_name['data_format'].enum_type = _LIDARCALIBRATION_DATAFORMAT
_LIDARCALIBRATION_DATAFORMAT.containing_type = _LIDARCALIBRATION
_LIDARCAMERACALIBRATION.fields_by_name['camera_module'].enum_type = lt__protobuf_dot_common_dot_camera__id__pb2._CAMERAID
_LIDARCAMERACALIBRATION.fields_by_name['euler_xyz_rad'].message_type = lt__protobuf_dot_common_dot_point3f__pb2._POINT3F
_LIDARCAMERACALIBRATION.fields_by_name['translation_mm'].message_type = lt__protobuf_dot_common_dot_point3f__pb2._POINT3F
DESCRIPTOR.message_types_by_name['LidarHwInfo'] = _LIDARHWINFO
DESCRIPTOR.message_types_by_name['LidarCalibration'] = _LIDARCALIBRATION
DESCRIPTOR.message_types_by_name['LidarCameraCalibration'] = _LIDARCAMERACALIBRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarHwInfo = _reflection.GeneratedProtocolMessageType('LidarHwInfo', (_message.Message,), {
  'DESCRIPTOR' : _LIDARHWINFO,
  '__module__' : 'lt_protobuf.light_header.extra_sensors.lidar_data_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.LidarHwInfo)
  })
_sym_db.RegisterMessage(LidarHwInfo)

LidarCalibration = _reflection.GeneratedProtocolMessageType('LidarCalibration', (_message.Message,), {
  'DESCRIPTOR' : _LIDARCALIBRATION,
  '__module__' : 'lt_protobuf.light_header.extra_sensors.lidar_data_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.LidarCalibration)
  })
_sym_db.RegisterMessage(LidarCalibration)

LidarCameraCalibration = _reflection.GeneratedProtocolMessageType('LidarCameraCalibration', (_message.Message,), {
  'DESCRIPTOR' : _LIDARCAMERACALIBRATION,
  '__module__' : 'lt_protobuf.light_header.extra_sensors.lidar_data_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.LidarCameraCalibration)
  })
_sym_db.RegisterMessage(LidarCameraCalibration)


# @@protoc_insertion_point(module_scope)
