# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_protobuf/light_header/distortion.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lt_protobuf.common import point2f_pb2 as lt__protobuf_dot_common_dot_point2f__pb2
from lt_protobuf.light_header import rectanglei_pb2 as lt__protobuf_dot_light__header_dot_rectanglei__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_protobuf/light_header/distortion.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n)lt_protobuf/light_header/distortion.proto\x12\x04ltpb\x1a lt_protobuf/common/point2f.proto\x1a)lt_protobuf/light_header/rectanglei.proto\"\xd3\x05\n\nDistortion\x12/\n\npolynomial\x18\x01 \x01(\x0b\x32\x1b.ltpb.Distortion.Polynomial\x12!\n\x03\x63ra\x18\x02 \x01(\x0b\x32\x14.ltpb.Distortion.CRA\x12\x30\n\x08\x64ist_map\x18\x03 \x01(\x0b\x32\x1e.ltpb.Distortion.DistortionMap\x1a\xa7\x01\n\nPolynomial\x12(\n\x11\x64istortion_center\x18\x01 \x01(\x0b\x32\r.ltpb.Point2F\x12$\n\rnormalization\x18\x02 \x01(\x0b\x32\r.ltpb.Point2F\x12\x12\n\x06\x63oeffs\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x08\x66it_cost\x18\x04 \x01(\x02\x12#\n\tvalid_roi\x18\x05 \x01(\x0b\x32\x10.ltpb.RectangleI\x1a\xa0\x02\n\x03\x43RA\x12(\n\x11\x64istortion_center\x18\x01 \x01(\x0b\x32\r.ltpb.Point2F\x12\x17\n\x0fsensor_distance\x18\x02 \x01(\x02\x12\x1b\n\x13\x65xit_pupil_distance\x18\x03 \x01(\x02\x12\x12\n\npixel_size\x18\x04 \x01(\x02\x12\x1a\n\x03\x63ra\x18\x05 \x03(\x0b\x32\r.ltpb.Point2F\x12\x1d\n\x06\x63oeffs\x18\x06 \x03(\x0b\x32\r.ltpb.Point2F\x12\x10\n\x08\x66it_cost\x18\x07 \x01(\x02\x12#\n\tvalid_roi\x18\x08 \x01(\x0b\x32\x10.ltpb.RectangleI\x12\x16\n\x0elens_hall_code\x18\t \x01(\x02\x12\x1b\n\x13\x64istance_hall_ratio\x18\n \x01(\x02\x1ar\n\rDistortionMap\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x10\n\x08\x64\x65\x63imate\x18\x03 \x01(\r\x12\x14\n\x0cpixel_offset\x18\x04 \x01(\x08\x12\x1a\n\x03map\x18\x05 \x03(\x0b\x32\r.ltpb.Point2Fb\x06proto3'
  ,
  dependencies=[lt__protobuf_dot_common_dot_point2f__pb2.DESCRIPTOR,lt__protobuf_dot_light__header_dot_rectanglei__pb2.DESCRIPTOR,])




_DISTORTION_POLYNOMIAL = _descriptor.Descriptor(
  name='Polynomial',
  full_name='ltpb.Distortion.Polynomial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distortion_center', full_name='ltpb.Distortion.Polynomial.distortion_center', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalization', full_name='ltpb.Distortion.Polynomial.normalization', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coeffs', full_name='ltpb.Distortion.Polynomial.coeffs', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fit_cost', full_name='ltpb.Distortion.Polynomial.fit_cost', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_roi', full_name='ltpb.Distortion.Polynomial.valid_roi', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=445,
)

_DISTORTION_CRA = _descriptor.Descriptor(
  name='CRA',
  full_name='ltpb.Distortion.CRA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distortion_center', full_name='ltpb.Distortion.CRA.distortion_center', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_distance', full_name='ltpb.Distortion.CRA.sensor_distance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exit_pupil_distance', full_name='ltpb.Distortion.CRA.exit_pupil_distance', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_size', full_name='ltpb.Distortion.CRA.pixel_size', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cra', full_name='ltpb.Distortion.CRA.cra', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coeffs', full_name='ltpb.Distortion.CRA.coeffs', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fit_cost', full_name='ltpb.Distortion.CRA.fit_cost', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_roi', full_name='ltpb.Distortion.CRA.valid_roi', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lens_hall_code', full_name='ltpb.Distortion.CRA.lens_hall_code', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance_hall_ratio', full_name='ltpb.Distortion.CRA.distance_hall_ratio', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=736,
)

_DISTORTION_DISTORTIONMAP = _descriptor.Descriptor(
  name='DistortionMap',
  full_name='ltpb.Distortion.DistortionMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ltpb.Distortion.DistortionMap.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ltpb.Distortion.DistortionMap.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decimate', full_name='ltpb.Distortion.DistortionMap.decimate', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_offset', full_name='ltpb.Distortion.DistortionMap.pixel_offset', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map', full_name='ltpb.Distortion.DistortionMap.map', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=852,
)

_DISTORTION = _descriptor.Descriptor(
  name='Distortion',
  full_name='ltpb.Distortion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='polynomial', full_name='ltpb.Distortion.polynomial', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cra', full_name='ltpb.Distortion.cra', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_map', full_name='ltpb.Distortion.dist_map', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DISTORTION_POLYNOMIAL, _DISTORTION_CRA, _DISTORTION_DISTORTIONMAP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=852,
)

_DISTORTION_POLYNOMIAL.fields_by_name['distortion_center'].message_type = lt__protobuf_dot_common_dot_point2f__pb2._POINT2F
_DISTORTION_POLYNOMIAL.fields_by_name['normalization'].message_type = lt__protobuf_dot_common_dot_point2f__pb2._POINT2F
_DISTORTION_POLYNOMIAL.fields_by_name['valid_roi'].message_type = lt__protobuf_dot_light__header_dot_rectanglei__pb2._RECTANGLEI
_DISTORTION_POLYNOMIAL.containing_type = _DISTORTION
_DISTORTION_CRA.fields_by_name['distortion_center'].message_type = lt__protobuf_dot_common_dot_point2f__pb2._POINT2F
_DISTORTION_CRA.fields_by_name['cra'].message_type = lt__protobuf_dot_common_dot_point2f__pb2._POINT2F
_DISTORTION_CRA.fields_by_name['coeffs'].message_type = lt__protobuf_dot_common_dot_point2f__pb2._POINT2F
_DISTORTION_CRA.fields_by_name['valid_roi'].message_type = lt__protobuf_dot_light__header_dot_rectanglei__pb2._RECTANGLEI
_DISTORTION_CRA.containing_type = _DISTORTION
_DISTORTION_DISTORTIONMAP.fields_by_name['map'].message_type = lt__protobuf_dot_common_dot_point2f__pb2._POINT2F
_DISTORTION_DISTORTIONMAP.containing_type = _DISTORTION
_DISTORTION.fields_by_name['polynomial'].message_type = _DISTORTION_POLYNOMIAL
_DISTORTION.fields_by_name['cra'].message_type = _DISTORTION_CRA
_DISTORTION.fields_by_name['dist_map'].message_type = _DISTORTION_DISTORTIONMAP
DESCRIPTOR.message_types_by_name['Distortion'] = _DISTORTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Distortion = _reflection.GeneratedProtocolMessageType('Distortion', (_message.Message,), {

  'Polynomial' : _reflection.GeneratedProtocolMessageType('Polynomial', (_message.Message,), {
    'DESCRIPTOR' : _DISTORTION_POLYNOMIAL,
    '__module__' : 'lt_protobuf.light_header.distortion_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.Distortion.Polynomial)
    })
  ,

  'CRA' : _reflection.GeneratedProtocolMessageType('CRA', (_message.Message,), {
    'DESCRIPTOR' : _DISTORTION_CRA,
    '__module__' : 'lt_protobuf.light_header.distortion_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.Distortion.CRA)
    })
  ,

  'DistortionMap' : _reflection.GeneratedProtocolMessageType('DistortionMap', (_message.Message,), {
    'DESCRIPTOR' : _DISTORTION_DISTORTIONMAP,
    '__module__' : 'lt_protobuf.light_header.distortion_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.Distortion.DistortionMap)
    })
  ,
  'DESCRIPTOR' : _DISTORTION,
  '__module__' : 'lt_protobuf.light_header.distortion_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.Distortion)
  })
_sym_db.RegisterMessage(Distortion)
_sym_db.RegisterMessage(Distortion.Polynomial)
_sym_db.RegisterMessage(Distortion.CRA)
_sym_db.RegisterMessage(Distortion.DistortionMap)


_DISTORTION_POLYNOMIAL.fields_by_name['coeffs']._options = None
# @@protoc_insertion_point(module_scope)
