# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_protobuf/light_header/illuminance_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_protobuf/light_header/illuminance_data.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/lt_protobuf/light_header/illuminance_data.proto\x12\x04ltpb\"6\n\x0fIlluminanceData\x12\x10\n\x08lux_data\x18\x01 \x01(\x02\x12\x11\n\tlux_range\x18\x02 \x01(\x05\x62\x06proto3')
)




_ILLUMINANCEDATA = _descriptor.Descriptor(
  name='IlluminanceData',
  full_name='ltpb.IlluminanceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lux_data', full_name='ltpb.IlluminanceData.lux_data', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lux_range', full_name='ltpb.IlluminanceData.lux_range', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['IlluminanceData'] = _ILLUMINANCEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IlluminanceData = _reflection.GeneratedProtocolMessageType('IlluminanceData', (_message.Message,), {
  'DESCRIPTOR' : _ILLUMINANCEDATA,
  '__module__' : 'lt_protobuf.light_header.illuminance_data_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.IlluminanceData)
  })
_sym_db.RegisterMessage(IlluminanceData)


# @@protoc_insertion_point(module_scope)
