# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_protobuf/light_header/range2f.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_protobuf/light_header/range2f.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&lt_protobuf/light_header/range2f.proto\x12\x04ltpb\"+\n\x07Range2F\x12\x0f\n\x07min_val\x18\x01 \x01(\x02\x12\x0f\n\x07max_val\x18\x02 \x01(\x02\x62\x06proto3'
)




_RANGE2F = _descriptor.Descriptor(
  name='Range2F',
  full_name='ltpb.Range2F',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_val', full_name='ltpb.Range2F.min_val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_val', full_name='ltpb.Range2F.max_val', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Range2F'] = _RANGE2F
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Range2F = _reflection.GeneratedProtocolMessageType('Range2F', (_message.Message,), {
  'DESCRIPTOR' : _RANGE2F,
  '__module__' : 'lt_protobuf.light_header.range2f_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.Range2F)
  })
_sym_db.RegisterMessage(Range2F)


# @@protoc_insertion_point(module_scope)
