# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gps_data_legacy.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gps_data_legacy.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15gps_data_legacy.proto\x12\x04ltpb\"\xc1\x07\n\rGPSDataLegacy\x12\x12\n\x08latitude\x18\x01 \x01(\x01H\x00\x12\x13\n\tlongitude\x18\x02 \x01(\x01H\x01\x12\x13\n\ttimestamp\x18\x03 \x01(\x04H\x02\x12\r\n\x03\x64op\x18\x04 \x01(\x01H\x03\x12(\n\x05track\x18\x05 \x01(\x0b\x32\x19.ltpb.GPSDataLegacy.Track\x12,\n\x07heading\x18\x06 \x01(\x0b\x32\x1b.ltpb.GPSDataLegacy.Heading\x12.\n\x08\x61ltitude\x18\x07 \x01(\x0b\x32\x1c.ltpb.GPSDataLegacy.Altitude\x12\x0f\n\x05speed\x18\x08 \x01(\x01H\x04\x12?\n\x11processing_method\x18\t \x01(\x0e\x32$.ltpb.GPSDataLegacy.ProcessingMethod\x1aG\n\x05Track\x12\r\n\x05value\x18\x01 \x01(\x01\x12/\n\x03ref\x18\x02 \x01(\x0e\x32\".ltpb.GPSDataLegacy.ReferenceNorth\x1aI\n\x07Heading\x12\r\n\x05value\x18\x01 \x01(\x01\x12/\n\x03ref\x18\x02 \x01(\x0e\x32\".ltpb.GPSDataLegacy.ReferenceNorth\x1aM\n\x08\x41ltitude\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x32\n\x03ref\x18\x02 \x01(\x0e\x32%.ltpb.GPSDataLegacy.ReferenceAltitude\"H\n\x0eReferenceNorth\x12\x1c\n\x18REFERENCE_NORTH_MAGNETIC\x10\x00\x12\x18\n\x14REFERENCE_NORTH_TRUE\x10\x01\"5\n\x11ReferenceAltitude\x12 \n\x1cREFERENCE_ALTITUDE_SEA_LEVEL\x10\x00\"\xc1\x01\n\x10ProcessingMethod\x12\x1d\n\x19PROCESSING_METHOD_UNKNOWN\x10\x00\x12\x19\n\x15PROCESSING_METHOD_GPS\x10\x01\x12\x1c\n\x18PROCESSING_METHOD_CELLID\x10\x02\x12\x1a\n\x16PROCESSING_METHOD_WLAN\x10\x03\x12\x1c\n\x18PROCESSING_METHOD_MANUAL\x10\x04\x12\x1b\n\x17PROCESSING_METHOD_FUSED\x10\x05\x42\x13\n\x11optional_latitudeB\x14\n\x12optional_longitudeB\x14\n\x12optional_timestampB\x0e\n\x0coptional_dopB\x10\n\x0eoptional_speedb\x06proto3'
)



_GPSDATALEGACY_REFERENCENORTH = _descriptor.EnumDescriptor(
  name='ReferenceNorth',
  full_name='ltpb.GPSDataLegacy.ReferenceNorth',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REFERENCE_NORTH_MAGNETIC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REFERENCE_NORTH_TRUE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=571,
  serialized_end=643,
)
_sym_db.RegisterEnumDescriptor(_GPSDATALEGACY_REFERENCENORTH)

_GPSDATALEGACY_REFERENCEALTITUDE = _descriptor.EnumDescriptor(
  name='ReferenceAltitude',
  full_name='ltpb.GPSDataLegacy.ReferenceAltitude',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REFERENCE_ALTITUDE_SEA_LEVEL', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=645,
  serialized_end=698,
)
_sym_db.RegisterEnumDescriptor(_GPSDATALEGACY_REFERENCEALTITUDE)

_GPSDATALEGACY_PROCESSINGMETHOD = _descriptor.EnumDescriptor(
  name='ProcessingMethod',
  full_name='ltpb.GPSDataLegacy.ProcessingMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_GPS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_CELLID', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_WLAN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_MANUAL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_METHOD_FUSED', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=701,
  serialized_end=894,
)
_sym_db.RegisterEnumDescriptor(_GPSDATALEGACY_PROCESSINGMETHOD)


_GPSDATALEGACY_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='ltpb.GPSDataLegacy.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ltpb.GPSDataLegacy.Track.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ref', full_name='ltpb.GPSDataLegacy.Track.ref', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=415,
)

_GPSDATALEGACY_HEADING = _descriptor.Descriptor(
  name='Heading',
  full_name='ltpb.GPSDataLegacy.Heading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ltpb.GPSDataLegacy.Heading.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ref', full_name='ltpb.GPSDataLegacy.Heading.ref', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=490,
)

_GPSDATALEGACY_ALTITUDE = _descriptor.Descriptor(
  name='Altitude',
  full_name='ltpb.GPSDataLegacy.Altitude',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ltpb.GPSDataLegacy.Altitude.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ref', full_name='ltpb.GPSDataLegacy.Altitude.ref', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=569,
)

_GPSDATALEGACY = _descriptor.Descriptor(
  name='GPSDataLegacy',
  full_name='ltpb.GPSDataLegacy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ltpb.GPSDataLegacy.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ltpb.GPSDataLegacy.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ltpb.GPSDataLegacy.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dop', full_name='ltpb.GPSDataLegacy.dop', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track', full_name='ltpb.GPSDataLegacy.track', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='ltpb.GPSDataLegacy.heading', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='ltpb.GPSDataLegacy.altitude', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ltpb.GPSDataLegacy.speed', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processing_method', full_name='ltpb.GPSDataLegacy.processing_method', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GPSDATALEGACY_TRACK, _GPSDATALEGACY_HEADING, _GPSDATALEGACY_ALTITUDE, ],
  enum_types=[
    _GPSDATALEGACY_REFERENCENORTH,
    _GPSDATALEGACY_REFERENCEALTITUDE,
    _GPSDATALEGACY_PROCESSINGMETHOD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_latitude', full_name='ltpb.GPSDataLegacy.optional_latitude',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_longitude', full_name='ltpb.GPSDataLegacy.optional_longitude',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_timestamp', full_name='ltpb.GPSDataLegacy.optional_timestamp',
      index=2, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_dop', full_name='ltpb.GPSDataLegacy.optional_dop',
      index=3, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_speed', full_name='ltpb.GPSDataLegacy.optional_speed',
      index=4, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=993,
)

_GPSDATALEGACY_TRACK.fields_by_name['ref'].enum_type = _GPSDATALEGACY_REFERENCENORTH
_GPSDATALEGACY_TRACK.containing_type = _GPSDATALEGACY
_GPSDATALEGACY_HEADING.fields_by_name['ref'].enum_type = _GPSDATALEGACY_REFERENCENORTH
_GPSDATALEGACY_HEADING.containing_type = _GPSDATALEGACY
_GPSDATALEGACY_ALTITUDE.fields_by_name['ref'].enum_type = _GPSDATALEGACY_REFERENCEALTITUDE
_GPSDATALEGACY_ALTITUDE.containing_type = _GPSDATALEGACY
_GPSDATALEGACY.fields_by_name['track'].message_type = _GPSDATALEGACY_TRACK
_GPSDATALEGACY.fields_by_name['heading'].message_type = _GPSDATALEGACY_HEADING
_GPSDATALEGACY.fields_by_name['altitude'].message_type = _GPSDATALEGACY_ALTITUDE
_GPSDATALEGACY.fields_by_name['processing_method'].enum_type = _GPSDATALEGACY_PROCESSINGMETHOD
_GPSDATALEGACY_REFERENCENORTH.containing_type = _GPSDATALEGACY
_GPSDATALEGACY_REFERENCEALTITUDE.containing_type = _GPSDATALEGACY
_GPSDATALEGACY_PROCESSINGMETHOD.containing_type = _GPSDATALEGACY
_GPSDATALEGACY.oneofs_by_name['optional_latitude'].fields.append(
  _GPSDATALEGACY.fields_by_name['latitude'])
_GPSDATALEGACY.fields_by_name['latitude'].containing_oneof = _GPSDATALEGACY.oneofs_by_name['optional_latitude']
_GPSDATALEGACY.oneofs_by_name['optional_longitude'].fields.append(
  _GPSDATALEGACY.fields_by_name['longitude'])
_GPSDATALEGACY.fields_by_name['longitude'].containing_oneof = _GPSDATALEGACY.oneofs_by_name['optional_longitude']
_GPSDATALEGACY.oneofs_by_name['optional_timestamp'].fields.append(
  _GPSDATALEGACY.fields_by_name['timestamp'])
_GPSDATALEGACY.fields_by_name['timestamp'].containing_oneof = _GPSDATALEGACY.oneofs_by_name['optional_timestamp']
_GPSDATALEGACY.oneofs_by_name['optional_dop'].fields.append(
  _GPSDATALEGACY.fields_by_name['dop'])
_GPSDATALEGACY.fields_by_name['dop'].containing_oneof = _GPSDATALEGACY.oneofs_by_name['optional_dop']
_GPSDATALEGACY.oneofs_by_name['optional_speed'].fields.append(
  _GPSDATALEGACY.fields_by_name['speed'])
_GPSDATALEGACY.fields_by_name['speed'].containing_oneof = _GPSDATALEGACY.oneofs_by_name['optional_speed']
DESCRIPTOR.message_types_by_name['GPSDataLegacy'] = _GPSDATALEGACY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPSDataLegacy = _reflection.GeneratedProtocolMessageType('GPSDataLegacy', (_message.Message,), {

  'Track' : _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), {
    'DESCRIPTOR' : _GPSDATALEGACY_TRACK,
    '__module__' : 'gps_data_legacy_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.GPSDataLegacy.Track)
    })
  ,

  'Heading' : _reflection.GeneratedProtocolMessageType('Heading', (_message.Message,), {
    'DESCRIPTOR' : _GPSDATALEGACY_HEADING,
    '__module__' : 'gps_data_legacy_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.GPSDataLegacy.Heading)
    })
  ,

  'Altitude' : _reflection.GeneratedProtocolMessageType('Altitude', (_message.Message,), {
    'DESCRIPTOR' : _GPSDATALEGACY_ALTITUDE,
    '__module__' : 'gps_data_legacy_pb2'
    # @@protoc_insertion_point(class_scope:ltpb.GPSDataLegacy.Altitude)
    })
  ,
  'DESCRIPTOR' : _GPSDATALEGACY,
  '__module__' : 'gps_data_legacy_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.GPSDataLegacy)
  })
_sym_db.RegisterMessage(GPSDataLegacy)
_sym_db.RegisterMessage(GPSDataLegacy.Track)
_sym_db.RegisterMessage(GPSDataLegacy.Heading)
_sym_db.RegisterMessage(GPSDataLegacy.Altitude)


# @@protoc_insertion_point(module_scope)
