# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_protobuf/common/point2i.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_protobuf/common/point2i.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n lt_protobuf/common/point2i.proto\x12\x04ltpb\"\x1f\n\x07Point2I\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x62\x06proto3'
)




_POINT2I = _descriptor.Descriptor(
  name='Point2I',
  full_name='ltpb.Point2I',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ltpb.Point2I.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ltpb.Point2I.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Point2I'] = _POINT2I
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point2I = _reflection.GeneratedProtocolMessageType('Point2I', (_message.Message,), {
  'DESCRIPTOR' : _POINT2I,
  '__module__' : 'lt_protobuf.common.point2i_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.Point2I)
  })
_sym_db.RegisterMessage(Point2I)


# @@protoc_insertion_point(module_scope)
