# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_protobuf/common/type_value_pair.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_protobuf/common/type_value_pair.proto',
  package='ltpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n(lt_protobuf/common/type_value_pair.proto\x12\x04ltpb\",\n\rTypeValuePair\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3'
)




_TYPEVALUEPAIR = _descriptor.Descriptor(
  name='TypeValuePair',
  full_name='ltpb.TypeValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ltpb.TypeValuePair.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ltpb.TypeValuePair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['TypeValuePair'] = _TYPEVALUEPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypeValuePair = _reflection.GeneratedProtocolMessageType('TypeValuePair', (_message.Message,), {
  'DESCRIPTOR' : _TYPEVALUEPAIR,
  '__module__' : 'lt_protobuf.common.type_value_pair_pb2'
  # @@protoc_insertion_point(class_scope:ltpb.TypeValuePair)
  })
_sym_db.RegisterMessage(TypeValuePair)


# @@protoc_insertion_point(module_scope)
